In [1]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv('/content/titanic.csv')
data.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Braund,Mr. Owen Harris,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,Cumings,Mrs. John Bradley (Florence Briggs Thayer),female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Heikkinen,Miss. Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Futrelle,Mrs. Jacques Heath (Lily May Peel),female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Allen,Mr. William Henry,male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Lname        156 non-null    object
 4   Name         156 non-null    object
 5   Sex          156 non-null    object
 6   Age          126 non-null    float64
 7   SibSp        156 non-null    int64
 8   Parch        156 non-null    int64
 9   Ticket       156 non-null    object
 10  Fare         156 non-null    float64
 11  Cabin        31 non-null     object
 12  Embarked     155 non-null    object
dtypes: float64(2), int64(5), object(6)
memory usage: 16.0+ KB

In [8]:
data.head(10)

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Braund,Mr. Owen Harris,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,Cumings,Mrs. John Bradley (Florence Briggs Thayer),female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Heikkinen,Miss. Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Futrelle,Mrs. Jacques Heath (Lily May Peel),female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Allen,Mr. William Henry,male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,Moran,Mr. James,male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,McCarthy,Mr. Timothy J,male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,Palsson,Master. Gosta Leonard,male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,Johnson,Mrs. Oscar W (Elisabeth Vilhelmina Berg),female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,Nasser,Mrs. Nicholas (Adele Achem),female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
data.drop(0,axis=0,inplace=True) #For deleting cells axis 0 means row,1 means column

In [11]:
data.head(10)

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,Cumings,Mrs. John Bradley (Florence Briggs Thayer),female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Heikkinen,Miss. Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Futrelle,Mrs. Jacques Heath (Lily May Peel),female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Allen,Mr. William Henry,male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,Moran,Mr. James,male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,McCarthy,Mr. Timothy J,male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,Palsson,Master. Gosta Leonard,male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,Johnson,Mrs. Oscar W (Elisabeth Vilhelmina Berg),female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,Nasser,Mrs. Nicholas (Adele Achem),female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,Sandstrom,Miss. Marguerite Rut,female,4.0,1,1,PP 9549,16.7000,G6,S

In [ ]:
data.drop([1,2,3],axis=0,inplace=True)

In [14]:
data.head(10)

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,Allen,Mr. William Henry,male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,Moran,Mr. James,male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,McCarthy,Mr. Timothy J,male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,Palsson,Master. Gosta Leonard,male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,Johnson,Mrs. Oscar W (Elisabeth Vilhelmina Berg),female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,Nasser,Mrs. Nicholas (Adele Achem),female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,Sandstrom,Miss. Marguerite Rut,female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,Bonnell,Miss. Elizabeth,female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,Saundercock,Mr. William Henry,male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,Andersson,Mr. Anders Johan,male,39.0,1,5,347082,31.2750,NaN,S

In [16]:
data.drop([4,5],axis=0,inplace=False) in #this code data 4,5 row deleted but if you out head 10 it will not delete from data directly
#You need to asssign a variable

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,McCarthy,Mr. Timothy J,male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,Palsson,Master. Gosta Leonard,male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,Johnson,Mrs. Oscar W (Elisabeth Vilhelmina Berg),female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,Nasser,Mrs. Nicholas (Adele Achem),female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,Sandstrom,Miss. Marguerite Rut,female,4.0,1,1,PP 9549,16.7000,G6,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,Pears,Mrs. Thomas (Edith Wearne),female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,Meo,Mr. Alfonzo,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,van Billiard,Mr. Austin Blyler,male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,Olsen,Mr. Ole Martin,male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,Williams,Mr. Charles Duane,male,51.0,0,1,PC 17597,61.3792,NaN,C

In [17]:
data.head(10)

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,Allen,Mr. William Henry,male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,Moran,Mr. James,male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,McCarthy,Mr. Timothy J,male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,Palsson,Master. Gosta Leonard,male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,Johnson,Mrs. Oscar W (Elisabeth Vilhelmina Berg),female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,Nasser,Mrs. Nicholas (Adele Achem),female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,Sandstrom,Miss. Marguerite Rut,female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,Bonnell,Miss. Elizabeth,female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,Saundercock,Mr. William Henry,male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,Andersson,Mr. Anders Johan,male,39.0,1,5,347082,31.2750,NaN,S

In [19]:
data=data.drop([4,5],axis=0,inplace=False) #if we run oce it is giving error to avoid the error you can use error=ignore

KeyError: '[4, 5] not found in axis'

In [21]:
data.drop([4,5],axis=0,inplace=False,errors='ignore')

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,McCarthy,Mr. Timothy J,male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,Palsson,Master. Gosta Leonard,male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,Johnson,Mrs. Oscar W (Elisabeth Vilhelmina Berg),female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,Nasser,Mrs. Nicholas (Adele Achem),female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,Sandstrom,Miss. Marguerite Rut,female,4.0,1,1,PP 9549,16.7000,G6,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,Pears,Mrs. Thomas (Edith Wearne),female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,Meo,Mr. Alfonzo,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,van Billiard,Mr. Austin Blyler,male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,Olsen,Mr. Ole Martin,male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,Williams,Mr. Charles Duane,male,51.0,0,1,PC 17597,61.3792,NaN,C

In [22]:
data=data.drop([6,7]) #by default axis =0 by default inplace as false

In [23]:
data.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
8,9,1,3,Johnson,Mrs. Oscar W (Elisabeth Vilhelmina Berg),female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,Nasser,Mrs. Nicholas (Adele Achem),female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,Sandstrom,Miss. Marguerite Rut,female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,Bonnell,Miss. Elizabeth,female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,Saundercock,Mr. William Henry,male,20.0,0,0,A/5. 2151,8.0500,NaN,S

In [24]:
data=data.drop(index=[8,9])

In [27]:
data.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,Sandstrom,Miss. Marguerite Rut,female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,Bonnell,Miss. Elizabeth,female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,Saundercock,Mr. William Henry,male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,Andersson,Mr. Anders Johan,male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,Vestrom,Miss. Hulda Amanda Adolfina,female,14.0,0,0,350406,7.8542,NaN,S

In [28]:
data=data.drop(labels=[10,11])

In [30]:
data.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,13,0,3,Saundercock,Mr. William Henry,male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,Andersson,Mr. Anders Johan,male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,Vestrom,Miss. Hulda Amanda Adolfina,female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,Hewlett,Mrs. (Mary D Kingcome),female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,Rice,Master. Eugene,male,2.0,4,1,382652,29.1250,NaN,Q

In [32]:
data.index[0]

12

In [38]:
data=data.drop(data.index[0])

In [40]:
data.tail()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
151,152,1,1,Pears,Mrs. Thomas (Edith Wearne),female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,Meo,Mr. Alfonzo,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,van Billiard,Mr. Austin Blyler,male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,Olsen,Mr. Ole Martin,male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,Williams,Mr. Charles Duane,male,51.0,0,1,PC 17597,61.3792,NaN,C

In [41]:
data=data.drop(data.index[-1]) #for deleteing last index wise

In [43]:
data.tail()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
150,151,0,2,Bateman,Rev. Robert James,male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,Pears,Mrs. Thomas (Edith Wearne),female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,Meo,Mr. Alfonzo,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,van Billiard,Mr. Austin Blyler,male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,Olsen,Mr. Ole Martin,male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [45]:
 data.index[[1,3]]

Index([15, 17], dtype='int64')

In [47]:
data.drop(data.index[[1,3]])

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
14,15,0,3,Vestrom,Miss. Hulda Amanda Adolfina,female,14.0,0,0,350406,7.8542,NaN,S
16,17,0,3,Rice,Master. Eugene,male,2.0,4,1,382652,29.1250,NaN,Q
18,19,0,3,Vander Planke,Mrs. Julius (Emelia Maria Vandemoortele),female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,Fynney,Mr. Joseph J,male,35.0,0,0,239865,26.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,151,0,2,Bateman,Rev. Robert James,male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,Pears,Mrs. Thomas (Edith Wearne),female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,Meo,Mr. Alfonzo,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,van Billiard,Mr. Austin Blyler,male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,Olsen,Mr. Ole Martin,male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [49]:
data.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
14,15,0,3,Vestrom,Miss. Hulda Amanda Adolfina,female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,Hewlett,Mrs. (Mary D Kingcome),female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,Rice,Master. Eugene,male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,Williams,Mr. Charles Eugene,male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,Vander Planke,Mrs. Julius (Emelia Maria Vandemoortele),female,31.0,1,0,345763,18.0000,NaN,S

In [52]:
data.index[0:5]

RangeIndex(start=14, stop=19, step=1)

In [53]:
data=data.drop(data.index[0:5]) #for delete a range

In [54]:
data.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,20,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,Fynney,Mr. Joseph J,male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S

In [63]:
data.loc[data["Lname"]=='Fynney']

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
20,21,0,2,Fynney,Mr. Joseph J,male,35.0,0,0,239865,26.0,NaN,S

In [64]:
data.loc[data["Lname"]=='Beesley']

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
21,22,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0,D56,S

By drop you can delete and another method to delete is

In [67]:
data=data.loc[data["Lname"]!='Fynney'] #For dedleting data by name or something you can use drop also

In [68]:
data.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,20,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,22,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S

Dropping column

In [69]:
data.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,20,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,22,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S

In [73]:
df=data.copy()

In [74]:
df.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,20,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,22,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S

In [75]:
df.drop('PassengerId',axis=1,inplace=True)

In [76]:
df.head()

,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,1,3,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,1,1,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,0,3,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S

In [ ]:
df.drop(['Survived','Pclass'],axis=1,inplace=True)

In [79]:
df.head()

,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S

In [80]:
df.drop(['Survived','Pclass'],axis=1,inplace=False,errors='ignore')

,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...
150,Bateman,Rev. Robert James,male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,Pears,Mrs. Thomas (Edith Wearne),female,22.0,1,0,113776,66.6000,C2,S
152,Meo,Mr. Alfonzo,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,van Billiard,Mr. Austin Blyler,male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,Olsen,Mr. Ole Martin,male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [81]:
df=df.drop(columns='Name')

In [82]:
df.head()

         Lname     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
19  Masselmani  female   NaN      0      0    2649   7.2250   NaN        C
21     Beesley    male  34.0      0      0  248698  13.0000   D56        S
22     McGowan  female  15.0      0      0  330923   8.0292   NaN        Q
23      Sloper    male  28.0      0      0  113788  35.5000    A6        S
24     Palsson  female   8.0      3      1  349909  21.0750   NaN        S

In [83]:
df=df.drop(columns=['Lname','Sex'])

In [84]:
df.head()

     Age  SibSp  Parch  Ticket     Fare Cabin Embarked
19   NaN      0      0    2649   7.2250   NaN        C
21  34.0      0      0  248698  13.0000   D56        S
22  15.0      0      0  330923   8.0292   NaN        Q
23  28.0      0      0  113788  35.5000    A6        S
24   8.0      3      1  349909  21.0750   NaN        S

In [89]:
df.columns[2] #for access column by index

'Parch'

In [90]:
df.drop(df.columns[2],axis=1)

      Age  SibSp       Ticket     Fare Cabin Embarked
19    NaN      0         2649   7.2250   NaN        C
21   34.0      0       248698  13.0000   D56        S
22   15.0      0       330923   8.0292   NaN        Q
23   28.0      0       113788  35.5000    A6        S
24    8.0      3       349909  21.0750   NaN        S
..    ...    ...          ...      ...   ...      ...
150  51.0      0  S.O.P. 1166  12.5250   NaN        S
151  22.0      1       113776  66.6000    C2        S
152  55.5      0   A.5. 11206   8.0500   NaN        S
153  40.5      0     A/5. 851  14.5000   NaN        S
154   NaN      0    Fa 265302   7.3125   NaN        S

[135 rows x 6 columns]

In [92]:
df.drop(df.columns[[1,2]],axis=1)  # we are not giving inplace = true so it take default as false and it nopt directly remove columns from data

      Age       Ticket     Fare Cabin Embarked
19    NaN         2649   7.2250   NaN        C
21   34.0       248698  13.0000   D56        S
22   15.0       330923   8.0292   NaN        Q
23   28.0       113788  35.5000    A6        S
24    8.0       349909  21.0750   NaN        S
..    ...          ...      ...   ...      ...
150  51.0  S.O.P. 1166  12.5250   NaN        S
151  22.0       113776  66.6000    C2        S
152  55.5   A.5. 11206   8.0500   NaN        S
153  40.5     A/5. 851  14.5000   NaN        S
154   NaN    Fa 265302   7.3125   NaN        S

[135 rows x 5 columns]

In [94]:
df.drop(df.columns[[0,1]],axis=1,inplace=True)

In [95]:
df.head()

    Parch  Ticket     Fare Cabin Embarked
19      0    2649   7.2250   NaN        C
21      0  248698  13.0000   D56        S
22      0  330923   8.0292   NaN        Q
23      0  113788  35.5000    A6        S
24      1  349909  21.0750   NaN        S

In [96]:
df.head()

    Parch  Ticket     Fare Cabin Embarked
19      0    2649   7.2250   NaN        C
21      0  248698  13.0000   D56        S
22      0  330923   8.0292   NaN        Q
23      0  113788  35.5000    A6        S
24      1  349909  21.0750   NaN        S

In [97]:
df.iloc[:,1:3] #: means all rows and after that 1:# columns

          Ticket     Fare
19          2649   7.2250
21        248698  13.0000
22        330923   8.0292
23        113788  35.5000
24        349909  21.0750
..           ...      ...
150  S.O.P. 1166  12.5250
151       113776  66.6000
152   A.5. 11206   8.0500
153     A/5. 851  14.5000
154    Fa 265302   7.3125

[135 rows x 2 columns]

In [98]:
df.drop(df.iloc[:,1:3],axis=1,inplace=True)

In [99]:
df.head()

    Parch Cabin Embarked
19      0   NaN        C
21      0   D56        S
22      0   NaN        Q
23      0    A6        S
24      1   NaN        S

In [101]:
 df=data.copy()
 df.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,20,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,22,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S

In [104]:
df.drop(df.loc[:,'Lname':'Ticket'].columns,axis=1,inplace=True) #iloc is not use for string range so use loc

In [105]:
df.head()

    PassengerId  Survived  Pclass     Fare Cabin Embarked
19           20         1       3   7.2250   NaN        C
21           22         1       2  13.0000   D56        S
22           23         1       3   8.0292   NaN        Q
23           24         1       1  35.5000    A6        S
24           25         0       3  21.0750   NaN        S

For deleting list of columns

In [106]:
liscol=['PassengerId','Survived','Embarked']
df=df.drop(liscol,axis=1)

In [107]:
df.head()

    Pclass     Fare Cabin
19       3   7.2250   NaN
21       2  13.0000   D56
22       3   8.0292   NaN
23       1  35.5000    A6
24       3  21.0750   NaN

Rename columns

In [109]:
df=data.copy()
data.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,20,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,22,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S

In [111]:
df.rename(columns={'Fare':'Fees'},inplace=True)
df.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fees,Cabin,Embarked
19,20,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,22,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S

In [115]:
df.rename(columns={'PassengerId':'Pass id','Lname':'Last Name'},inplace=True)

In [116]:
df.head()

,Pass id,Survived,Pclass,Last Name,Name,Sex,Age,SibSp,Parch,Ticket,Fees,Cabin,Embarked
19,20,1,3,Masselmani,Mrs. Fatima,female,NaN,0,0,2649,7.2250,NaN,C
21,22,1,2,Beesley,Mr. Lawrence,male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,McGowan,Miss. Anna,female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,Sloper,Mr. William Thompson,male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,Palsson,Miss. Torborg Danira,female,8.0,3,1,349909,21.0750,NaN,S